### PR TITLE
Add DBeaver section

### PR DESCRIPTION
**Pull request by gramian**
* Added section on DBeaver (Section 7.6)

### CODE REVIEW

**Comment by gramian** [comment]
* I also completed the distance function table (Section 2.2.6)

**Comment by lvca** [comment]
Wdyt about moving dbeaver under a new section "Compatible Tools"? I could add DbVisualizer too

**Comment by gramian** [comment]
* Added a new section "Compatible Tools" (Section 7.13) and moved DBeaver subsection there.

**Comment by lvca** [comment]
Perfect, thanks!

**Pull request merged**
